### ISSUE TITLE
我在运行项目时出现了问题

### ISSUE THREAD

**Issue by shenyi1** [Aqua-Dream/Tieba_Spider#30]
### 我在第一次运行项目时，修改了config.json文件后，出现了如下错误：我用的是scrapy 2.4.0 
`E:\Pycharmprojects\tieba>scrapy run 仙五前修改 Pal5Q_Diy
Traceback (most recent call last):
  File "E:\anaconda3\Scripts\scrapy-script.py", line 10, in <module>
    sys.exit(execute())
  File "E:\anaconda3\lib\site-packages\scrapy\cmdline.py", line 142, in execute
    _run_print_help(parser, cmd.process_options, args, opts)
  File "E:\anaconda3\lib\site-packages\scrapy\cmdline.py", line 100, in _run_print_help
    func(*a, **kw)
  File "E:\anaconda3\lib\site-packages\scrapy\commands\__init__.py", line 130, in process_options
    if opts.output or opts.overwrite_output:
AttributeError: 'Values' object has no attribute 'overwrite_output'
`

**Comment by shenyi1** [comment]
该问题已解决：我的python版本是3.7.1 可能是最新的scrapy兼容问题，卸载scrapy2.4.0重新安装scrapy1.8.0即可
`pip uninstall scrapy 
pip install scrapy==1.8.0`
查看自己的scrapy版本
`scrapy version -v`
