### ISSUE TITLE
AttributeError: 'Values' object has no attribute 'overwrite_output'

### ISSUE THREAD

**Issue by jjshare** [Aqua-Dream/Tieba_Spider#32]
✗ scrapy run                             
Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 8, in <module>
    sys.exit(execute())
  File "/Users/noname/Library/Python/3.8/lib/python/site-packages/scrapy/cmdline.py", line 142, in execute
    _run_print_help(parser, cmd.process_options, args, opts)
  File "/Users/noname/Library/Python/3.8/lib/python/site-packages/scrapy/cmdline.py", line 100, in _run_print_help
    func(*a, **kw)
  File "/Users/noname/Library/Python/3.8/lib/python/site-packages/scrapy/commands/__init__.py", line 130, in process_options
    if opts.output or opts.overwrite_output:
AttributeError: 'Values' object has no attribute 'overwrite_output'

**Comment by Aqua-Dream** [comment]
Seems not an issue from Tieba_Spider. Can you provide your scrapy version? And under which folder were you executing the command "scrapy run"?

**Comment by projektarbeit1** [comment]
楼主，你好，我的也是相同的情况，出现了value object has no attribute  overwrite_output，能帮我看看吗？谢谢了。我附上截图
![Uploading issue.JPG…]()

**Comment by Aqua-Dream** [comment]
> 楼主，你好，我的也是相同的情况，出现了value object has no attribute overwrite_output，能帮我看看吗？谢谢了。我附上截图

图片无法打开，确认上传成功？

**Comment by projektarbeit1** [comment]
![issue](https://user-images.githubusercontent.com/14888198/106547282-e7255900-6547-11eb-95eb-1d5eb240d6c3.JPG)

**Comment by Aqua-Dream** [comment]
> 楼主，你好，我的也是相同的情况，出现了value object has no attribute overwrite_output，能帮我看看吗？谢谢了。我附上截图

麻烦提供下scrapy版本号，以及你报错时从输入命令到最后一行输出的所有内容(复制到这里来)

**Comment by projektarbeit1** [comment]
现在上传成功了，能否帮我看看啊，谢谢啦

config.json文件我也已经更改了，我装的是mysql workbench 8.0

Scrapy == 2.4.1

(base) C:\AAAAAA\Project\Spider\Tieba_Spider>scrapy run thinkpad
Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\scrapy-script.py", line 10, in <module>
    sys.exit(execute())
  File "C:\Anaconda3\lib\site-packages\scrapy\cmdline.py", line 142, in execute
    _run_print_help(parser, cmd.process_options, args, opts)
  File "C:\Anaconda3\lib\site-packages\scrapy\cmdline.py", line 100, in _run_print_help
    func(*a, **kw)
  File "C:\Anaconda3\lib\site-packages\scrapy\commands\__init__.py", line 130, in process_options
    if opts.output or opts.overwrite_output:
AttributeError: 'Values' object has no attribute 'overwrite_output'

**Comment by Joker931a** [comment]
你好，我也遇到了这个问题，能否请大神解决一下呢？
Scarpy==2.5.1 下面是问题原因
D:\pycharm\pythonenvironmentlist\venv\Scripts\python.exe D:/test/pyqt_main.py
Traceback (most recent call last):
  File "C:\Users\joker931\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\joker931\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\pycharm\pythonenvironmentlist\venv\Scripts\scrapy.exe\__main__.py", line 7, in <module>
  File "D:\pycharm\pythonenvironmentlist\venv\lib\site-packages\scrapy\cmdline.py", line 142, in execute
    _run_print_help(parser, cmd.process_options, args, opts)
  File "D:\pycharm\pythonenvironmentlist\venv\lib\site-packages\scrapy\cmdline.py", line 100, in _run_print_help
    func(*a, **kw)
  File "D:\pycharm\pythonenvironmentlist\venv\lib\site-packages\scrapy\commands\__init__.py", line 132, in process_options
    if opts.output or opts.overwrite_output:
AttributeError: 'Values' object has no attribute 'overwrite_output'

Process finished with exit code 0

**Comment by Aqua-Dream** [comment]
> 你好，我也遇到了这个问题，能否请大神解决一下呢？ Scarpy==2.5.1 下面是问题原因 D:\pycharm\pythonenvironmentlist\venv\Scripts\python.exe D:/test/pyqt_main.py Traceback (most recent call last): File "C:\Users\joker931\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main "**main**", mod_spec) File "C:\Users\joker931\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "D:\pycharm\pythonenvironmentlist\venv\Scripts\scrapy.exe__main__.py", line 7, in File "D:\pycharm\pythonenvironmentlist\venv\lib\site-packages\scrapy\cmdline.py", line 142, in execute _run_print_help(parser, cmd.process_options, args, opts) File "D:\pycharm\pythonenvironmentlist\venv\lib\site-packages\scrapy\cmdline.py", line 100, in _run_print_help func(*a, **kw) File "D:\pycharm\pythonenvironmentlist\venv\lib\site-packages\scrapy\commands__init__.py", line 132, in process_options if opts.output or opts.overwrite_output: AttributeError: 'Values' object has no attribute 'overwrite_output'
> 
> Process finished with exit code 0

看起来像和楼上一样的问题。你确定文件是用的最新版吗？

**Comment by Joker931a** [comment]
是最新版，刚刚安装的。难道是实际代码与现在的scarpy包不适配吗

**Comment by Joker931a** [comment]
是的，昨天刚更新安装的，难道是代码与新版的Scarpy包不适配吗

**Comment by Aqua-Dream** [comment]
看来版本更新又改接口了，有毒。我有空的时候弄一下。

**Comment by Aqua-Dream** [comment]
请降级scrapy到2.4.1再试试。更新接口的话，旧版本的用户就没法用了

**Comment by Joker931a** [comment]
好像还是不行，我试了试降到2.4.1 和2.4.0 问题还是一样的，我还是问问学长们吧，感谢大佬
下方是问题。
D:\pycharm\pythonenvironmentlist\venv\Scripts\python.exe D:/test/pyqt_main.py
Traceback (most recent call last):
  File "C:\Users\joker931\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\joker931\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\pycharm\pythonenvironmentlist\venv\Scripts\scrapy.exe\__main__.py", line 7, in <module>
  File "D:\pycharm\pythonenvironmentlist\venv\lib\site-packages\scrapy\cmdline.py", line 142, in execute
    _run_print_help(parser, cmd.process_options, args, opts)
  File "D:\pycharm\pythonenvironmentlist\venv\lib\site-packages\scrapy\cmdline.py", line 100, in _run_print_help
    func(*a, **kw)
  File "D:\pycharm\pythonenvironmentlist\venv\lib\site-packages\scrapy\commands\__init__.py", line 130, in process_options
    if opts.output or opts.overwrite_output:
AttributeError: 'Values' object has no attribute 'overwrite_output'

Process finished with exit code 0

**Comment by falcolee** [comment]
commands/run.py文件中缺少process_options函数，加上之后即可，
在scrapy 2.5.1最新版 python3.8环境下可用 
class Command(crawl.Command):
 def process_options(self, args, opts):
        ScrapyCommand.process_options(self, args, opts)
