### ISSUE TITLE
看不出什么问题了，help

### ISSUE THREAD

**Issue by woody3rd** [Aqua-Dream/Tieba_Spider#42]
(venv) woody@Woody-MacBookPro tieba-spider % scrapy run java woody
Traceback (most recent call last):
  File "/Users/woody/workspace/life/tieba-spider/venv/bin/scrapy", line 8, in <module>
    sys.exit(execute())
  File "/Users/woody/workspace/life/tieba-spider/venv/lib/python3.10/site-packages/scrapy/cmdline.py", line 140, in execute
    cmd.add_options(parser)
  File "/Users/woody/workspace/life/tieba-spider/tieba/commands/run.py", line 19, in add_options
    parser.add_option("-a", dest="spargs", action="append", default=[], metavar="NAME=VALUE",
AttributeError: 'ArgumentParser' object has no attribute 'add_option'. Did you mean: '_add_action'?

**Comment by MTzeyang** [comment]
改成add_argument
